### ISSUE TITLE
SKIDDED SKIDDED SKIDDED

### ISSUE THREAD

**Issue by pyrgasm** [adzinoo/discord-token-generator#2]
SKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDED

NOW CHANGE MI TITLE SKIDDIE

**Comment by pyrgasm** [comment]
CHange it you shit

**Comment by pyrgasm** [comment]
CHange it you shit

**Comment by pyrgasm** [comment]
Yu lil rapper

**Comment by d0c-cpu** [comment]
https://github.com/Its-Vichy/working-token-gen
original gen
https://github.com/Its-Vichy/working-token-gen
https://github.com/Its-Vichy/working-token-gen
https://github.com/Its-Vichy/working-token-gen
https://github.com/Its-Vichy/working-token-gen 

SKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDEDSKIDDED SKIDDED SKIDDED- dumb retard

**Comment by adzinoo** [comment]
that gen is literally from 2020 :sob: it doesnt work no more , so idk what u mean by skidded
